Repository unb-mds/2024-2-SuaFinanca, pull requests merged in 2025-01, with the labels that each got.

#38 feat(docs): protótipo de alta fidelidade atualizado
  documents/doc/prototype/highFidelity.md
Labels: documentation

#51 Feat: add feature that allows the user to delete their account
  backend/http/users.http
  backend/prisma/schema.prisma
  backend/src/application/interfaces/domain/entities/user/IauthUser.ts
  backend/src/application/useCases/deleteUserUseCase.ts
  backend/src/infrastructure/database/prisma/prismaAuthUser.ts
  backend/src/main/config/dependencyInjection/userDependencyInjection.ts
  backend/src/main/config/helpers/protocol/user/deleteUserProtocols.ts
  backend/src/main/config/helpers/useCases/IuseCases.ts
  backend/src/main/controllers/user/deleteUserController.ts
  backend/src/main/routes/user/userRoutes.ts
  backend/src/main/routes/user/userServiceRoutes.ts
  backend/src/types/express.d.ts
Labels: feature

#56 feat: add the system to delete the categories
  backend/http/category.http
  backend/src/application/interfaces/domain/entities/category/IcategoryRepository.ts
  backend/src/application/useCases/category/deleteCategoryUseCase.ts
  backend/src/infrastructure/database/prisma/prismaCategoryRepository.ts
  backend/src/main/config/dependencyInjection/categoryDependencyInjection.ts
  backend/src/main/config/helpers/useCases/IuseCases.ts
  backend/src/main/controllers/category/deleteCategoryController.ts
  backend/src/main/routes/category/categoryRoutes.ts
  backend/src/main/routes/category/categoryServiceRoutes.ts
Labels: feature

#55 test: add unit tests for controllers and category creation use cases
  backend/test/category/controllers/createCategoryController.spec.ts
  backend/test/category/controllers/getCategoriesByUserController.spec.ts
  backend/test/category/useCases/createCategoryUseCase.spec.ts
  backend/test/category/useCases/getCategoriesUseCase.spec.ts
Labels: Test

#52 feat: add the system for creating financial transactions
  backend/http/transaction.http
  backend/prisma/schema.prisma
  backend/src/application/interfaces/domain/entities/transaction/ItransactionRepository.ts
  backend/src/application/interfaces/services/IgetCategoryService.ts
  backend/src/application/services/createTransactionSchema.ts
  backend/src/application/services/getCategoryService.ts
  backend/src/application/useCases/transaction/createTransactionUseCase.ts
  backend/src/domain/entities/Transaction.ts
  backend/src/infrastructure/database/inMemoryRepository/inMemoryTransactionRepository.ts
  backend/src/infrastructure/database/prisma/prismaTransactionRepository.ts
  backend/src/main/config/dependencyInjection/transactionDependencyInjection.ts
  backend/src/main/config/helpers/protocol/transaction/createTransactionProtocols.ts
  backend/src/main/config/helpers/useCases/IuseCases.ts
  backend/src/main/controllers/transaction/createTransactionController.ts
  backend/src/main/routes/transaction/transactionRoutes.ts
  backend/src/main/routes/transaction/transactionServiceRoutes.ts
  backend/src/server.ts
Labels: feature

#58 Doc/sprint/sprint 7
  documents/doc/sprints/sprint_0.md
  documents/doc/sprints/sprint_1.md
  documents/doc/sprints/sprint_2.md
  documents/doc/sprints/sprint_3.md
  documents/doc/sprints/sprint_4.md
  documents/doc/sprints/sprint_5.md
  documents/doc/sprints/sprint_6.md
  documents/doc/sprints/sprint_7.md
Labels: documentation

#60 feat: add the system to update categories
  backend/http/category.http
  backend/http/users.http
  backend/src/application/interfaces/domain/entities/category/IcategoryRepository.ts
  backend/src/application/services/updateCategorySchema.ts
  backend/src/application/useCases/category/updateCategoryUseCase.ts
  backend/src/infrastructure/database/prisma/prismaCategoryRepository.ts
  backend/src/main/config/dependencyInjection/categoryDependencyInjection.ts
  backend/src/main/config/helpers/protocol/category/updateCategoryProtocols.ts
  backend/src/main/config/helpers/useCases/IuseCases.ts
  backend/src/main/controllers/category/updateCategoryController.ts
  backend/src/main/controllers/user/deleteUserController.ts
  backend/src/main/routes/category/categoryRoutes.ts
  backend/src/main/routes/category/categoryServiceRoutes.ts
  backend/src/main/routes/user/userRoutes.ts
  backend/src/main/routes/user/userServiceRoutes.ts
Labels: feature

#64 feat: add unit tests for the financial transaction creation system
  backend/test/transaction/controllers/createTransactionController.spec.ts
  backend/test/transaction/useCases/createTransactionUseCase.spec.ts
  backend/vitest.config.ts
Labels: Test

#65 test: add unit tests to delete the user
  backend/src/infrastructure/database/inMemoryRepository/inMemoryAuthUserRepository.ts
  backend/test/user/controllers/deleteUserController.spec.ts
  backend/test/user/useCases/deleteUserUseCase.spec.ts
Labels: Test

#66 test: add unit tests to exclude categories
  backend/src/domain/entities/Category.ts
  backend/src/infrastructure/database/inMemoryRepository/inMemoryCategoryRepository.ts
  backend/test/category/controllers/deleteCategoryController.spec.ts
  backend/test/category/useCases/deleteCategoryUseCase.spec.ts
Labels: Test

#67 test: add unit tests to update categories
  backend/test/category/controllers/updateCategoryController.spec.ts
  backend/test/category/useCases/updateCategoryUseCase.spec.ts
Labels: Test

#68 ci(ci.yml): add the github actions file to run the linter and tests on the backend
  .github/workflows/ci.yml
Labels: feature

#82 docs(pull_request_template): add pull request on the project
  .github/pull_request_template.md
Labels: documentation

#78 docs(code_of_conduct): add code of conduct.
  CODE_OF_CONDUCT.md
Labels: documentation

#69 feat: Add user customization
  .github/workflows/ci.yml
  backend/http/users.http
  backend/src/application/interfaces/domain/entities/user/IauthUser.ts
  backend/src/application/services/updateUserSchema.ts
  backend/src/application/useCases/updateUserUseCase.ts
  backend/src/infrastructure/database/prisma/prismaAuthUser.ts
  backend/src/main/config/dependencyInjection/userDependencyInjection.ts
  backend/src/main/config/helpers/protocol/user/updateUserProtocols.ts
  backend/src/main/config/helpers/useCases/IuseCases.ts
  backend/src/main/controllers/user/updateUserController.ts
  backend/src/main/routes/user/userRoutes.ts
  backend/src/main/routes/user/userServiceRoutes.ts
Labels: feature

#80 docs(security_policy): add security policy
  SECURITY.md
Labels: documentation

#79 docs(contributing): add contributing.
  CONTRIBUTING.md
Labels: documentation

#89 docs(extreme_programing): Add XP documentation
  documents/doc/extreme_programing_experience.md
Labels: documentation

#95 Update SECURITY.md
  SECURITY.md
Labels: documentation
