Repository unb-mds/2024-2-SuaFinanca, pull requests merged in 2025-02, with the labels that each got.

#103 Fix: fix In Memory Auth User Repository
  backend/src/infrastructure/database/inMemoryRepository/inMemoryAuthUserRepository.ts
  backend/src/infrastructure/database/inMemoryRepository/inMemoryTransactionRepository.ts
  backend/src/infrastructure/database/prisma/prismaAuthUser.ts
  backend/test/transaction/useCases/createTransactionUseCase.spec.ts
Labels: bug

#99 feat: add a route to get the user's latest transactions
  backend/http/transaction.http
  backend/src/application/interfaces/domain/entities/transaction/ItransactionRepository.ts
  backend/src/application/useCases/transaction/getRecentTransactionsUseCase.ts
  backend/src/infrastructure/database/inMemoryRepository/inMemoryTransactionRepository.ts
  backend/src/infrastructure/database/prisma/prismaTransactionRepository.ts
  backend/src/main/config/dependencyInjection/transactionDependencyInjection.ts
  backend/src/main/config/helpers/protocol/transaction/getRecentTransactionsProtocols.ts
  backend/src/main/config/helpers/useCases/IuseCases.ts
  backend/src/main/controllers/transaction/getRecentTransactionsController.ts
  backend/src/main/routes/transaction/transactionRoutes.ts
  backend/src/main/routes/transaction/transactionServiceRoutes.ts
  backend/test/transaction/controllers/getRecentTransactionsController.spec.ts
  backend/test/transaction/useCases/getRecentTransactionsUseCase.spec.ts
Labels: feature

#104 feat: delete transaction feature
  backend/http/transaction.http
  backend/src/application/interfaces/domain/entities/transaction/ItransactionRepository.ts
  backend/src/application/useCases/transaction/deleteTransactionUseCase.ts
  backend/src/infrastructure/database/inMemoryRepository/inMemoryTransactionRepository.ts
  backend/src/infrastructure/database/prisma/prismaTransactionRepository.ts
  backend/src/main/config/dependencyInjection/transactionDependencyInjection.ts
  backend/src/main/config/helpers/protocol/transaction/deleteTransactionProtocols.ts
  backend/src/main/config/helpers/useCases/IuseCases.ts
  backend/src/main/controllers/transaction/deleteTransactionController.ts
  backend/src/main/routes/transaction/transactionRoutes.ts
  backend/src/main/routes/transaction/transactionServiceRoutes.ts
Labels: feature

#86 feat: criação da página de receitas
  frontend/app/receitas/nova/nova-receita.css
  frontend/app/receitas/nova/page.tsx
  frontend/app/receitas/page.tsx
  frontend/app/receitas/receitas.css
Labels: feature

#114 doc: add documentation of sprint 8
  documents/doc/sprints/sprint_8.md
Labels: documentation

#106 doc: add backend's README
  backend/README.md
Labels: documentation

#124 test: add unit tests that was missing on the project
  backend/src/application/services/createUserSchema.ts
  backend/src/application/services/updateUserSchema.ts
  backend/test/transaction/controllers/deleteTransactionController.spec.ts
  backend/test/transaction/controllers/updateTransactionController.spec.ts
  backend/test/transaction/useCases/deleteTransactionUseCase.spec.ts
  backend/test/transaction/useCases/updateTransactionUseCase.spec.ts
  backend/test/user/controllers/updateUserController.spec.ts
  backend/test/user/useCases/updateUserUseCase.spec.ts
  backend/vitest.config.ts
Labels: Test

#119 feat(feature): adds automated tests to the frontend/dashboard
  .github/workflows/ci.yml
  frontend/app/contexts/mocks/AuthContext.tsx
  frontend/app/dashboard/dashboard.test.tsx
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
Labels: feature

#113 feat: add the necessary tools for the backend build process
  .github/workflows/ci.yml
  backend/.gitignore
  backend/eslint.config.mjs
  backend/package-lock.json
  backend/package.json
  backend/src/main/config/logs/log.ts
  backend/src/server.ts
  backend/tsconfig.json
Labels: enhancement

#127 feat: add the description parameter to financial transactions
  backend/package-lock.json
  backend/package.json
  backend/prisma/schema.prisma
  backend/src/application/interfaces/domain/entities/transaction/ItransactionRepository.ts
  backend/src/application/schema/category/createCategorySchema.ts
  backend/src/application/schema/category/updateCategorySchema.ts
  backend/src/application/schema/transaction/createTransactionSchema.ts
  backend/src/application/schema/transaction/updateTransactionSchema.ts
  backend/src/application/schema/user/createUserSchema.ts
  backend/src/application/schema/user/updateUserSchema.ts
  backend/src/application/services/getCategoryService.ts
  backend/src/application/useCases/transaction/updateTransactionUseCase.ts
  backend/src/application/useCases/user/createUseCases.ts
  backend/src/application/useCases/user/deleteUserUseCase.ts
  backend/src/application/useCases/user/loginUserUseCase.ts
  backend/src/application/useCases/user/updateUserUseCase.ts
  backend/src/domain/entities/Transaction.ts
  backend/src/infrastructure/database/prisma/prismaTransactionRepository.ts
  backend/src/main/config/dependencyInjection/userDependencyInjection.ts
  backend/src/main/config/helpers/protocol/transaction/updateTransactionProtocols.ts
  backend/src/main/controllers/category/createCategoryController.ts
  backend/src/main/controllers/category/updateCategoryController.ts
  backend/src/main/controllers/transaction/createTransactionController.ts
  backend/src/main/controllers/transaction/getRecentTransactionsController.ts
  backend/src/main/controllers/transaction/getUserBalanceSummaryController.ts
  backend/src/main/controllers/transaction/updateTransactionController.ts
  backend/src/main/controllers/user/createUserController.ts
  backend/src/main/controllers/user/updateUserController.ts
  backend/test/transaction/controllers/createTransactionController.spec.ts
  backend/test/transaction/controllers/deleteTransactionController.spec.ts
  backend/test/transaction/controllers/getRecentTransactionsController.spec.ts
  backend/test/transaction/controllers/getUserBalanceSummaryController.spec.ts
  backend/test/transaction/useCases/createTransactionUseCase.spec.ts
  backend/test/transaction/useCases/getRecentTransactionsUseCase.spec.ts
  backend/test/transaction/useCases/getUserBalanceUseCase.spec.ts
  backend/test/transaction/useCases/updateTransactionUseCase.spec.ts
  backend/test/user/controllers/createUserController.spec.ts
  backend/test/user/controllers/deleteUserController.spec.ts
  backend/test/user/controllers/loginUserController.spec.ts
  backend/test/user/controllers/updateUserController.spec.ts
  backend/test/user/useCases/createUseCases.spec.ts
  backend/test/user/useCases/deleteUserUseCase.spec.ts
  backend/test/user/useCases/loginUseCases.spec.ts
  backend/test/user/useCases/updateUserUseCase.spec.ts
Labels: feature, Test

#129 refactor: update email uniqueness validation and display of category names
  backend/src/application/useCases/transaction/getRecentTransactionsUseCase.ts
  backend/src/application/useCases/user/updateUserUseCase.ts
  backend/src/domain/entities/Transaction.ts
  backend/src/main/config/dependencyInjection/transactionDependencyInjection.ts
  backend/src/main/controllers/transaction/getRecentTransactionsController.ts
  backend/src/main/controllers/transaction/getUserBalanceSummaryController.ts
  backend/test/transaction/controllers/getRecentTransactionsController.spec.ts
  backend/test/transaction/controllers/getUserBalanceSummaryController.spec.ts
  backend/test/transaction/useCases/getRecentTransactionsUseCase.spec.ts
  backend/test/user/useCases/updateUserUseCase.spec.ts
Labels: enhancement

#130 Back 94/document/document all routes
  backend/src/main/config/swaggerConfig.ts
  backend/src/main/routes/category/categoryRoutes.ts
  backend/src/main/routes/transaction/transactionRoutes.ts
  backend/src/main/routes/user/userRoutes.ts
Labels: documentation, feature

#132 Front/lint/add-linter
  .github/workflows/ci.yml
  frontend/.eslintrc.json
  frontend/.prettierrc.json
  frontend/app/components/Layout.tsx
  frontend/app/contexts/AuthContext.tsx
  frontend/app/dashboard/dashboard.test.tsx
  frontend/app/dashboard/page.tsx
  frontend/app/despesas/nova/page.tsx
  frontend/app/despesas/page.tsx
  frontend/app/layout.tsx
  frontend/app/login/page.tsx
  frontend/app/metas/page.tsx
  frontend/app/page.tsx
  frontend/app/receitas/nova/page.tsx
  frontend/app/receitas/page.tsx
  frontend/app/register/page.tsx
  frontend/app/relatorios/page.tsx
  frontend/app/saldo/page.tsx
  frontend/app/transacoes/page.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
Labels: bug

#134 docs: add sprint's documentation and update mkdocs
  README.md
  documents/doc/sprints/sprint_10.md
  documents/doc/sprints/sprint_11.md
  documents/doc/sprints/sprint_9.md
  documents/index.md
  mkdocs.yml
Labels: documentation
